module NpnAttributes where

npnAttributes :: [String]
npnAttributes = [
  "brojna",
  "dana",
  "definirana",
  "inozemna",
  "inspirirana",
  "izložena",
  "kemijska",
  "najteža",
  "neriješena",
  "ostala",
  "podijeljena",
  "postavljana",
  "potkrijepljena",
  "potrošena",
  "praktična",
  "prekrivena",
  "radna",
  "rađena",
  "relevantna",
  "riješena",
  "spomenuta",
  "strana",
  "strateška",
  "ukrašena",
  "uspješna",
  "uvedena",
  "uvrštena",
  "uzrokovana",
  "vezana",
  "zaključena",
  "znatna" ]
